# Generated by Django 3.2.20 on 2023-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_contactform_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
