# Generated by Django 3.2.20 on 2023-08-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_contactenquiry_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
