# Generated by Django 3.2.20 on 2023-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230811_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
