# Generated by Django 3.2.20 on 2023-08-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_contactenquiry_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
