# Generated by Django 3.2.20 on 2023-08-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_profile_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_image2',
        ),
    ]
